### ISSUE TITLE
Can't print, hi, in the old ZOLA I used to see a small printer icon so I could print the lot to have as a reference to draw in autocad. I can't print now, there is no option, am I missing somethig? Thank you.

### ISSUE THREAD

**Issue by arcomfenix** [NYCPlanning/labs-planninglabs-home#11]
#### User Story
As a {type of user}, I want {some goal} so that {some reason}

#### Description
What's it all about?
Hi, in the old ZOLA I used to see a small printer icon so I could print the lot to have as a reference to draw in autocad. I can't print now, there is no option, am I missing somethig? Thank you.

#### What should happen:
Wer should be able to print from the screen I guess...
#### What happened instead:
No icon or option to print.
#### How to reproduce this bug:
Actually is not a bug. 
1. Step one
2. ???
3. Error

#### Browser(s) and Device(s) observed on:
Chrome, in a Windows 7 Computer.

**Comment by chriswhong** [comment]
Hi, this is the wrong repo to open an issue for ZoLa.

Incidentally, you can print in ZoLa by using your web browser's print function.  Use `control-p` or go the `File` menu and select `Print...`

If you have further issues you can open an issue in the ZoLa Repo:
https://github.com/NYCPlanning/labs-zola/issues
