### ISSUE TITLE
Incorrect zoning district in right panel

### ISSUE THREAD

**Issue by geojanes** [NYCPlanning/labs-planninglabs-home#7]
#### Browser(s) and Device(s) observed on: Windows 10 Chrome

![screenshot 2017-12-19 22 31 08](https://user-images.githubusercontent.com/34700406/34190228-9a2b5310-e50d-11e7-9f04-e229fa8a1c45.png)

![screenshot 2017-12-19 22 31 32](https://user-images.githubusercontent.com/34700406/34190242-ab5fd67e-e50d-11e7-9533-c2cfad500d09.png)

**Comment by chriswhong** [comment]
Hi, I think this belongs in https://github.com/nycplanning/labs-zola.  This repo is for the planning labs home site at planninglabs.nyc.
