### ISSUE TITLE
Menu wraps to below logo on IE11/Windows 7

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-planninglabs-home#9]
#### What should happen:
The menu items should appear inline with the logo on medium and large screens.

#### What happened instead:
The menu items wrap to a new line underneath the logo, and the icons/text appear spread out.

#### How to reproduce this bug:

Load planninglabs.nyc on IE11/Windows 7

#### Browser(s) and Device(s) observed on:

IE11/Windows 7
<img width="1094" alt="dashboard" src="https://user-images.githubusercontent.com/1833820/36127049-6a0ff5f4-1029-11e8-9719-57ed0d795f1e.png">

**Comment by andycochran** [comment]
One-line fix. 

![image](https://user-images.githubusercontent.com/409279/36132070-20198090-1043-11e8-9eea-d8d05e053b6d.png)

The width of the SVG is set to auto. 
If we set an explicit width, the menu no longer wraps.

**Comment by chriswhong** [comment]
Closed by 99d5b1385410775d1f866e1e2e8765727d9303b5
